# Generated by Django 4.2.6 on 2024-11-19 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_saving_special_cnd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depositoption",
            name="deposit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="products.deposit",
            ),
        ),
        migrations.AlterField(
            model_name="savingoption",
            name="saving",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="products.saving",
            ),
        ),
    ]
