# Generated by Django 4.2.6 on 2024-11-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_depositoption_intr_rate2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="user_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="saving",
            name="user_change",
            field=models.BooleanField(default=False),
        ),
    ]
