# Generated by Django 4.2.6 on 2024-11-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_deposit_user_change_saving_user_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositoption",
            name="user_change",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="savingoption",
            name="user_change",
            field=models.BooleanField(default=False),
        ),
    ]
