# Generated by Django 4.2.6 on 2024-11-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_depositoption_user_change_savingoption_user_change"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deposit",
            name="user_change",
        ),
        migrations.RemoveField(
            model_name="saving",
            name="user_change",
        ),
    ]
